FROM debian:jessie

LABEL PRADEEP <pradeepbaradur6@gmail.com>

RUN apt-get update && apt-get install -y \
    nginx nginx-extras

ADD nginx.conf /etc/nginx/
ADD backend.conf /etc/nginx/sites-available/

RUN ln -s /etc/nginx/sites-available/backend.conf /etc/nginx/sites-enabled/backend
RUN rm /etc/nginx/sites-enabled/default

RUN usermod -u 1000 www-data

CMD ["nginx"]

EXPOSE 80
